-- Add unique constraint on name for ON CONFLICT (skip if exists)
DO $$
BEGIN
  ALTER TABLE "exercises" ADD CONSTRAINT exercises_name_key UNIQUE (name);
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- Seed 100 weightlifting & crossfit exercises (skip if name exists)
INSERT INTO "exercises" (name, category, unit) VALUES
  ('Back Squat', 'compound', 'kg'),
  ('Front Squat', 'compound', 'kg'),
  ('Overhead Squat', 'compound', 'kg'),
  ('Air Squat', 'compound', 'reps'),
  ('Conventional Deadlift', 'compound', 'kg'),
  ('Sumo Deadlift', 'compound', 'kg'),
  ('Romanian Deadlift', 'compound', 'kg'),
  ('Power Clean', 'compound', 'kg'),
  ('Squat Clean', 'compound', 'kg'),
  ('Hang Power Clean', 'compound', 'kg'),
  ('Power Snatch', 'compound', 'kg'),
  ('Squat Snatch', 'compound', 'kg'),
  ('Push Jerk', 'compound', 'kg'),
  ('Split Jerk', 'compound', 'kg'),
  ('Shoulder Press', 'compound', 'kg'),
  ('Push Press', 'compound', 'kg'),
  ('Bench Press', 'compound', 'kg'),
  ('Incline Bench Press', 'compound', 'kg'),
  ('Thruster', 'compound', 'kg'),
  ('Sumo Deadlift High Pull', 'compound', 'kg'),
  ('Barbell Row', 'compound', 'kg'),
  ('Pendlay Row', 'compound', 'kg'),
  ('Leg Press', 'compound', 'kg'),
  ('Hack Squat', 'compound', 'kg'),
  ('Bulgarian Split Squat', 'compound', 'kg'),
  ('Lunges', 'compound', 'kg'),
  ('Walking Lunges', 'compound', 'kg'),
  ('Goblet Squat', 'compound', 'kg'),
  ('Kettlebell Goblet Squat', 'compound', 'kg'),
  ('Overhead Press', 'compound', 'kg'),
  ('Strict Press', 'compound', 'kg'),
  ('Dumbbell Bench Press', 'compound', 'kg'),
  ('Dumbbell Row', 'compound', 'kg'),
  ('Dumbbell Shoulder Press', 'compound', 'kg'),
  ('Dumbbell Curl', 'isolation', 'kg'),
  ('Hammer Curl', 'isolation', 'kg'),
  ('Tricep Pushdown', 'isolation', 'kg'),
  ('Skull Crushers', 'isolation', 'kg'),
  ('Close Grip Bench', 'compound', 'kg'),
  ('Lat Pulldown', 'compound', 'kg'),
  ('Cable Row', 'compound', 'kg'),
  ('Face Pull', 'isolation', 'kg'),
  ('Lateral Raise', 'isolation', 'kg'),
  ('Front Raise', 'isolation', 'kg'),
  ('Reverse Fly', 'isolation', 'kg'),
  ('Leg Extension', 'isolation', 'kg'),
  ('Leg Curl', 'isolation', 'kg'),
  ('Calf Raise', 'isolation', 'kg'),
  ('Hip Thrust', 'compound', 'kg'),
  ('Glute Bridge', 'compound', 'kg'),
  ('Good Morning', 'compound', 'kg'),
  ('Pull-Up', 'compound', 'reps'),
  ('Chin-Up', 'compound', 'reps'),
  ('Strict Pull-Up', 'compound', 'reps'),
  ('Kipping Pull-Up', 'compound', 'reps'),
  ('Chest-to-Bar', 'compound', 'reps'),
  ('Muscle-Up', 'compound', 'reps'),
  ('Ring Muscle-Up', 'compound', 'reps'),
  ('Bar Muscle-Up', 'compound', 'reps'),
  ('Push-Up', 'compound', 'reps'),
  ('Handstand Push-Up', 'compound', 'reps'),
  ('Ring Dips', 'compound', 'reps'),
  ('Bar Dips', 'compound', 'reps'),
  ('Pike Push-Up', 'compound', 'reps'),
  ('Toes-to-Bar', 'compound', 'reps'),
  ('Knee-to-Elbow', 'compound', 'reps'),
  ('V-Up', 'compound', 'reps'),
  ('GHD Sit-Up', 'compound', 'reps'),
  ('Hollow Hold', 'compound', 'time'),
  ('L-Sit', 'compound', 'time'),
  ('Plank', 'compound', 'time'),
  ('Ring Row', 'compound', 'reps'),
  ('Inverted Row', 'compound', 'reps'),
  ('Pistol Squat', 'compound', 'reps'),
  ('Box Jump', 'cardio', 'reps'),
  ('Box Step-Up', 'compound', 'kg'),
  ('Wall Ball', 'compound', 'kg'),
  ('Kettlebell Swing', 'compound', 'kg'),
  ('American Kettlebell Swing', 'compound', 'kg'),
  ('Russian Kettlebell Swing', 'compound', 'kg'),
  ('Kettlebell Snatch', 'compound', 'kg'),
  ('Kettlebell Clean', 'compound', 'kg'),
  ('Kettlebell Goblet Press', 'compound', 'kg'),
  ('Turkish Get-Up', 'compound', 'kg'),
  ('Farmer Carry', 'compound', 'kg'),
  ('Suitcase Carry', 'compound', 'kg'),
  ('Burpee', 'cardio', 'reps'),
  ('Burpee Over Bar', 'cardio', 'reps'),
  ('Double Under', 'cardio', 'reps'),
  ('Single Under', 'cardio', 'reps'),
  ('Rope Climb', 'compound', 'reps'),
  ('Sled Push', 'compound', 'kg'),
  ('Sled Pull', 'compound', 'kg'),
  ('Bike', 'cardio', 'time'),
  ('Row', 'cardio', 'time'),
  ('Assault Bike', 'cardio', 'time'),
  ('Ski Erg', 'cardio', 'time'),
  ('Snatch Grip Deadlift', 'compound', 'kg'),
  ('Deficit Deadlift', 'compound', 'kg'),
  ('Pause Squat', 'compound', 'kg'),
  ('Tempo Squat', 'compound', 'kg'),
  ('Zercher Squat', 'compound', 'kg'),
  ('Safety Bar Squat', 'compound', 'kg'),
  ('Landmine Row', 'compound', 'kg'),
  ('Landmine Press', 'compound', 'kg'),
  ('Cable Fly', 'isolation', 'kg'),
  ('Pec Deck', 'isolation', 'kg'),
  ('Preacher Curl', 'isolation', 'kg'),
  ('Concentration Curl', 'isolation', 'kg'),
  ('Overhead Tricep Extension', 'isolation', 'kg'),
  ('Dips', 'compound', 'reps'),
  ('Cable Crossover', 'isolation', 'kg'),
  ('Shrugs', 'isolation', 'kg'),
  ('Upright Row', 'compound', 'kg'),
  ('Curl to Press', 'compound', 'kg'),
  ('Man Makers', 'compound', 'kg'),
  ('Renegade Row', 'compound', 'kg'),
  ('Mountain Climbers', 'cardio', 'reps'),
  ('Jump Squat', 'compound', 'kg'),
  ('Tuck Jump', 'cardio', 'reps')
ON CONFLICT (name) DO NOTHING;
